name: 🐛 Bug
description: Use this template to report an bug/error to help improve the project
title: '[BUG] <description>'
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the bug
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Please add the steps to reproduce the problem
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
