name: Other
description: Use this template for any other issues
title: '[OTHER] <description>'
labels: ['other']
body:
  - type: markdown
    attributes:
      value: '# Other issue'
  - type: textarea
    id: issuedescription
    attributes:
      label: What would you like to share?
      description: Provide a clear and concise explanation of your issue
    validations:
      required: true
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false